title: "Charlotte's Portfolio"
description: "A showcase of my projects, experience, and education."
baseurl: "" # Leave empty for GitHub Pages
url: "https://coforgeyjahn.github.io/charlotte_portfolio" # Replace <username> and <repository> with your GitHub info

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
